name: CI

on:
  push:
  pull_request:

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  cargo-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Format and Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Test
        run: |
          cargo check
          cargo test --all
      - name: Build
        run: |
          cd phaser
          cargo build --release
