name: CI

on:
  push:
  pull_request:

jobs:
  cargo-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup component add rustfmt
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Clean
        run: |
          cargo clean
      - name: Format and Lint
        run: |
          cargo fmt
          cargo clippy
      - name: Test
        run: |
          cargo check
          cargo test --all
      - name: Build
        run: |
          cargo build --release